Assessments

In [2]:
import pandas as pd
fruits = ["apples", "oranges", "cherries", "pears"]
fruits_ro = ["mere", "portocale", "cirese", "pere"]
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 311, 32], index=fruits_ro)
print(S+S2)

apples      NaN
cherries    NaN
cirese      NaN
mere        NaN
oranges     NaN
pears       NaN
pere        NaN
portocale   NaN
dtype: float64


In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

1. Hassan has five kinds of dogs which are husky, pitbull, shepherd, bulldog and eskimo.
Create a python program such that anyone can check if Hassan has a particular breed, if the breed is in the list of dogs print 'present' else print 'absent'. Note: use your input and conditional statements.


In [ ]:
hassan_dogs = ['husky','pitbull','shepherd','bulldog','eskimo']
check_dog = input('Enter the dog breed You are looking for: ')
if check_dog in hassan_dogs:
  print('Present')
else:
  print('Absent')

Enter the dog breed You are looking for: rott
Absent


2. Write a python program to reverse names.
E.g aloba - abola, aishat - tahsia



In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr[1::2, :2]

array([[ 4,  5],
       [10, 11]])

3. Create a lambda function that can add two numbers and gives a result.
e.g, addition of 2 and 3 should give 5.
Use a lambda function.



4. Write a function that calculates the area of a rectangle.



In [ ]:
import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 50, size=(5, 5))
print("Generated Numpy Array:")
print(arr)

Generated Numpy Array:
[[45 48  1  4  4]
 [40 10 20 22 37]
 [24  7 25 25 13]
 [ 2 39 40 24 47]
 [25 18 38 26 14]]


5.  How can I index 38 from the array



6. From the array in question 5. How can I slice out [25, 25, 13], [40 , 24, 47], [38, 26, 14]


7. Create an array of zeroes of shape, (2,5)



8. Create an array of ones of shape (2,5)



9. Create an array full of 6, of shape(4,4)



10. Create a numpy array of shape (3,3) with random integers between 1 and 100.

**<h1><center>Pandas Assessment<center></h1>**

**<h1>Online Food Order Dataset</h1>**

**<h1>Description:</h1>**
The dataset contains information collected from an online food ordering platform over a period of time. It encompasses various attributes related to Occupation, Family Size, Feedback etc..

**<h1>Attributes:</h1>**

**<h2>Demographic Information:</h2>**

**Age:** Age of the customer.

**Gender:** Gender of the customer.

**Marital Status:** Marital status of the customer.

**Occupation:** Occupation of the customer.

**Monthly Income:** Monthly income of the customer.

**Educational Qualifications:** Educational qualifications of the customer.

**Family Size:** Number of individuals in the customer's family.

**<h2>Location Information:</h2>**

**Latitude:**Latitude of the customer's location.

**Longitude:** Longitude of the customer's location.

**Pin Code:** Pin code of the customer's location.
Order Details:**

**<h2>Purpose:</h2>**
This dataset can be utilized to explore the relationship between demographic/location factors and online food ordering behavior, analyze customer feedback to improve service quality, and potentially predict customer preferences or behavior based on demographic and location attributes.

11. Read in the dataset

In [ ]:
df = pd.read_csv()

Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes

12. Check the head of the data to get the first 10 rows

13. Get the statistical information about the dataset

14. Check for the sum of missing values in each column

15. Do we have duplicates in the data, if we have duplicates drop them

16. What is the maximum Age in the dataset?

17. What is the minimum Age in the dataset?

18. What is the mean Age in the dataset?

19. Do Males buy food online more than the Females

In [ ]:
df['Family size'].value_counts()

Family size
3    117
2    101
4     63
5     54
6     29
1     24
Name: count, dtype: int64

20. Do you think Singles buy food more or Married people, write a code for that

21. Let's analyse the Feedback. Do people give positive feedbacks

22. Use the groupby function to groupby Gender and Marital Status, then see the average age.

**<h1>Visualization</h1>**

23. Use the plotly package to create a histogram for the Age column

24. Use the plotly package to create a bar chart for the Marital Status Column

25. Use the plotly package to create a bar chart for the Gender column

26. Use the plotly package to create a bar chart for the Occupation Column

27. Use the plotly package to create a pie chart for the Gender column

28. Use the plotly package to create a bar chart for the Marital Status Column, use the Gender as the legend

29. Use the plotly package to create a bar chart for the Gender column, use Feedback as the legend

30. Use the plotly package to create a bar chart for the Monthly Income Column and use the Gender for the legend

31. Create a boxplot for the Age column

32. Create a boxplot, use gender as the x axis and Age for the y-axis

33. Create a boxplot, use Marital Status as the x axis and Age for the y-axis

34. Create a Violin Plot, use Monthly Income as the x axis and Age for the y-axis

35. Create a Scatter plot, use the Latitude as x-axis and Longitude as y-axis.

36. Create a Bubble plot, use the Latitude as x-axis and Longitude as y-axis, Use the Age as the size.