In [2]:
import numpy as np

In [3]:
# creating the "grades" array from the grades list

grades = [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]

grades = np.array(grades)

In [4]:
# Using numpy functions to calculate the mean of the grades
np.mean(grades)

87.5

In [ ]:
# Using numpy functions to calculate the median of the grades

np.median(grades)

88.5

In [ ]:
# Using numpy functions to calculate the standard deviation of the grades

np.std(grades)

6.591661399070799

In [ ]:
# Using numpy function to find the maximum of the grades

np.max(grades)

98

In [ ]:
# Using numpy function to find the minimum of the grades

np.min(grades)

75

In [ ]:
# Using numpy function to sort the grades in ascending order.

np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [ ]:
# Using numpy function to find the index of the highest grade in the array.

np.argmax(grades)

7

In [34]:
# Using numpy function to count the number of students who scored above 90.

np.count_nonzero(grades>90)

3

In [35]:
# Using numpy function to calculate the percentage of students who scored above 90.

np.mean(grades > 90) * 100

30.0

In [36]:
# Using numpy function to calculate the percentage of students who scored below 75.

np.mean(grades < 75) * 100

0.0

In [6]:
# Using numpy function to extract all the grades above 90 and put them in a new array called "high_performers".

high_performers = grades[grades>90]
high_performers

array([92, 95, 98])

In [8]:
# Creating a new array called "passing_grades" that contains all the grades above 75.

passing_grades = grades[grades>75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])